import type { ManufacturingRecipeDefinition } from '@/types/game.types';

export const MANUFACTURING_RECIPES: Record<string, ManufacturingRecipeDefinition> = {
  'smelt-refined-metals': {
    id: 'smelt-refined-metals',
    name: 'Smelt Refined Metals',
    description: 'Melt raw ore into pure refined metals.',
    inputs: { 'raw-ore': 5 },
    outputs: { 'refined-metals': 1 },
    timeCost: 5,
  },
  'fabricate-silicon-wafers': {
    id: 'fabricate-silicon-wafers',
    name: 'Fabricate Silicon Wafers',
    description: 'Cut and polish silicon crystals into precision wafers.',
    inputs: { 'silicon-crystals': 3 },
    outputs: { 'silicon-wafers': 1 },
    timeCost: 5,
  },
  'forge-structural-alloys': {
    id: 'forge-structural-alloys',
    name: 'Forge Structural Alloys',
    description: 'Combine refined metals and carbon into high-strength alloys.',
    inputs: { 'refined-metals': 3, 'carbon-materials': 2 },
    outputs: { 'structural-alloys': 1 },
    timeCost: 10,
    prerequisiteResearch: 'industrial-manufacturing-i',
  },
  'synthesize-industrial-polymers': {
    id: 'synthesize-industrial-polymers',
    name: 'Synthesize Industrial Polymers',
    description: 'Process carbon materials into industrial-grade polymers.',
    inputs: { 'carbon-materials': 4 },
    outputs: { 'industrial-polymers': 1 },
    timeCost: 8,
    prerequisiteResearch: 'industrial-manufacturing-i',
  },
  'extract-hydrogen-fuel': {
    id: 'extract-hydrogen-fuel',
    name: 'Extract Hydrogen Fuel',
    description: 'Electrolysis of ice deposits yields hydrogen fuel.',
    inputs: { 'ice-deposits': 3 },
    outputs: { 'hydrogen-fuel': 1 },
    timeCost: 6,
  },
  'assemble-machine-parts': {
    id: 'assemble-machine-parts',
    name: 'Assemble Machine Parts',
    description: 'Precision assembly of mechanical components from alloys.',
    inputs: { 'structural-alloys': 2, 'refined-metals': 1 },
    outputs: { 'machine-parts': 1 },
    timeCost: 15,
    prerequisiteResearch: 'industrial-manufacturing-i',
  },
  'fabricate-drone-components': {
    id: 'fabricate-drone-components',
    name: 'Fabricate Drone Components',
    description: 'Modular drone assembly from structural and electronic parts.',
    inputs: { 'structural-alloys': 1, 'silicon-wafers': 2, 'machine-parts': 1 },
    outputs: { 'drone-components': 1 },
    timeCost: 20,
    prerequisiteResearch: 'ai-basic-automation',
  },
  'manufacture-energy-cells': {
    id: 'manufacture-energy-cells',
    name: 'Manufacture Energy Cells',
    description: 'Compact energy storage cells from advanced materials.',
    inputs: { 'structural-alloys': 1, 'silicon-wafers': 3, 'hydrogen-fuel': 1 },
    outputs: { 'energy-cells': 1 },
    timeCost: 20,
    prerequisiteResearch: 'energy-fusion-basics',
  },
  'print-quantum-circuits': {
    id: 'print-quantum-circuits',
    name: 'Print Quantum Circuits',
    description: 'Nanoscale photolithography for quantum computing substrates.',
    inputs: { 'silicon-wafers': 5, 'energy-cells': 1, 'nano-assemblies': 1 },
    outputs: { 'quantum-circuits': 1 },
    timeCost: 30,
    prerequisiteResearch: 'industrial-manufacturing-ii',
  },
};

export const RECIPE_ORDER = [
  'smelt-refined-metals',
  'fabricate-silicon-wafers',
  'forge-structural-alloys',
  'synthesize-industrial-polymers',
  'extract-hydrogen-fuel',
  'assemble-machine-parts',
  'fabricate-drone-components',
  'manufacture-energy-cells',
  'print-quantum-circuits',
];
