import type { ResearchNodeDefinition } from '@/types/game.types';

export const RESEARCH_NODES: Record<string, ResearchNodeDefinition> = {
  // ── Industrial ─────────────────────────────────────────────────────────
  'industrial-mining-ii': {
    id: 'industrial-mining-ii',
    name: 'Advanced Asteroid Mining',
    description: 'Improved targeting systems unlock metallic and carbon asteroid fields.',
    category: 'industrial',
    tier: 1,
    depth: 1,
    baseCost: { 'raw-ore': 200 },
    baseTime: 30,
    prerequisites: [],
    effects: [{ modifier: 'mining-efficiency', value: 0.05 }],
    unlocks: ['metallic-asteroid-field', 'carbon-asteroid-belt'],
  },
  'industrial-laser-refinement': {
    id: 'industrial-laser-refinement',
    name: 'Laser Refinement',
    description: 'High-frequency lasers improve ore extraction precision by 10%.',
    category: 'industrial',
    tier: 1,
    depth: 2,
    baseCost: { 'raw-ore': 500, 'refined-metals': 10 },
    baseTime: 60,
    prerequisites: ['industrial-mining-ii'],
    effects: [{ modifier: 'mining-efficiency', value: 0.10 }],
    unlocks: ['mining-laser-ii'],
  },
  'industrial-manufacturing-i': {
    id: 'industrial-manufacturing-i',
    name: 'Manufacturing Basics',
    description: 'Automated manufacturing protocols for component production.',
    category: 'industrial',
    tier: 1,
    depth: 1,
    baseCost: { 'refined-metals': 30 },
    baseTime: 45,
    prerequisites: [],
    effects: [],
    unlocks: ['system-manufacturing'],
  },
  'industrial-manufacturing-ii': {
    id: 'industrial-manufacturing-ii',
    name: 'Advanced Manufacturing',
    description: 'Parallel production lines increase manufacturing speed by 50%.',
    category: 'industrial',
    tier: 2,
    depth: 2,
    baseCost: { 'refined-metals': 200, 'machine-parts': 5 },
    baseTime: 120,
    prerequisites: ['industrial-manufacturing-i'],
    effects: [{ modifier: 'manufacturing-speed', value: 0.50 }],
    unlocks: [],
  },

  // ── Energy ─────────────────────────────────────────────────────────────
  'energy-fusion-basics': {
    id: 'energy-fusion-basics',
    name: 'Fusion Power Basics',
    description: 'Controlled hydrogen fusion enables high-output reactors.',
    category: 'energy',
    tier: 1,
    depth: 1,
    baseCost: { 'hydrogen-fuel': 20, 'silicon-wafers': 10 },
    baseTime: 60,
    prerequisites: [],
    effects: [{ modifier: 'energy-efficiency', value: 0.10 }],
    unlocks: ['fusion-reactor'],
  },
  'energy-grid-optimization': {
    id: 'energy-grid-optimization',
    name: 'Grid Optimization',
    description: 'Smart grid management reduces energy consumption by 15%.',
    category: 'energy',
    tier: 2,
    depth: 2,
    baseCost: { 'silicon-wafers': 50, 'quantum-circuits': 2 },
    baseTime: 90,
    prerequisites: ['energy-fusion-basics'],
    effects: [{ modifier: 'energy-demand-reduction', value: 0.15 }],
    unlocks: [],
  },
  'energy-stellar-tap': {
    id: 'energy-stellar-tap',
    name: 'Stellar Energy Tapping',
    description: 'Breakthrough technology to harvest energy from stellar radiation.',
    category: 'energy',
    tier: 3,
    depth: 3,
    baseCost: { 'exotic-matter': 2, 'quantum-circuits': 10 },
    baseTime: 300,
    prerequisites: ['energy-grid-optimization'],
    effects: [{ modifier: 'energy-efficiency', value: 0.25 }],
    unlocks: ['stellar-harvester'],
  },

  // ── AI / Automation ────────────────────────────────────────────────────
  'ai-basic-automation': {
    id: 'ai-basic-automation',
    name: 'Basic AI Automation',
    description: 'Simple AI routines enable autonomous mining drones.',
    category: 'ai',
    tier: 1,
    depth: 1,
    baseCost: { 'silicon-wafers': 30, 'raw-ore': 100 },
    baseTime: 60,
    prerequisites: [],
    effects: [],
    unlocks: ['drone-coordinator', 'automation-tier-1'],
  },

  // ── Exploration ────────────────────────────────────────────────────────
  'exploration-remote-sensing': {
    id: 'exploration-remote-sensing',
    name: 'Remote Sensing Arrays',
    description: 'Long-range sensors identify ice asteroid clusters for mining.',
    category: 'exploration',
    tier: 1,
    depth: 1,
    baseCost: { 'silicon-crystals': 50, 'raw-ore': 100 },
    baseTime: 45,
    prerequisites: [],
    effects: [],
    unlocks: ['ice-asteroid-cluster'],
  },
  'exploration-deep-scan': {
    id: 'exploration-deep-scan',
    name: 'Deep Scan Arrays',
    description: 'Penetrating scan technology reveals rare mineral deposits.',
    category: 'exploration',
    tier: 2,
    depth: 2,
    baseCost: { 'silicon-wafers': 20, 'energy-cells': 5 },
    baseTime: 90,
    prerequisites: ['exploration-remote-sensing'],
    effects: [{ modifier: 'mining-rare-bonus', value: 0.05 }],
    unlocks: ['deep-scan-array'],
  },
};

export const RESEARCH_CATEGORY_LABELS: Record<string, string> = {
  industrial: 'Industrial',
  energy: 'Energy',
  ai: 'AI Systems',
  exploration: 'Exploration',
};
